1. debug git clone

diff --git a/docker/create/dockerfile b/docker/create/dockerfile
--- a/docker/create/dockerfile
+++ b/docker/create/dockerfile
@@ -19,10 +19,11 @@ RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/
 RUN apt install git -y;
 RUN apt install vim -y;
 
-
 # next-doc pull
+COPY ./docker/create/create_env.sh /root/script/create_env.sh
 RUN {\
   git clone https://github.com/d3v-friends/next-docs /root/next-docs; \
+  sh /root/script/create_env.sh || {echo "fail env"; exit 1;} \
   npm i -g pnpm; \
   cd /root/next-docs; \
   pnpm install; \
@@ -30,6 +31,7 @@ RUN {\
 };
 
 # next build
-WORKDIR /root
+WORKDIR /root/next-docs
 
-ENTRYPOINT ["/root/vscode/code","tunnel"]
+CMD ["pnpm", "run", "start"]
+
